[theme]
primaryColor = "#D4AF37"          #Gold / Brass Real
backgroundColor = "#0B0C10"       #Dark Obsidian
secondaryBackgroundColor = "#0A192F" #Deep Blue Navy
textColor = "#D2C4AE"             #Cinza Concreto
font = "sans serif"